"""New fields

Revision ID: 18903eab5c15
Revises: 29b26a35d871
Create Date: 2022-05-06 21:50:36.419578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18903eab5c15'
down_revision = '29b26a35d871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
