"""Adds bio and profile path models

Revision ID: 25204e0aeecd
Revises: bd42d1c1d42e
Create Date: 2022-05-06 19:17:48.129246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25204e0aeecd'
down_revision = 'bd42d1c1d42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
