"""Adds pass-secure Migration - Adds pass

Revision ID: bd42d1c1d42e
Revises: 5cff2da57dc7
Create Date: 2022-05-06 18:45:01.368672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd42d1c1d42e'
down_revision = '5cff2da57dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
